pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}

rootProject.name = "ethora-sample-android"

include(":app")

// -----------------------------------------------------------------------
// Optional composite build for local SDK iteration.
//
// If an ethora-sdk-android checkout is available on disk, compile the
// sample against its source directly via includeBuild instead of
// pulling a pre-built AAR from JitPack. Keeps the
//   implementation("com.github.dappros:ethora-sdk-android:<ver>")
// line in app/build.gradle.kts unchanged — external consumers are
// unaffected — and removes the 3-5 minute JitPack roundtrip from the
// inner-loop SDK edit → rebuild sample flow.
//
// Resolution order (first match wins):
//   1. $ETHORA_SDK_LOCAL_PATH  — explicit override
//   2. ../ethora-sdk-android             — plain side-by-side clones
//   3. ../ethora-bdsm/product/ethora-sdk-android    — BDSM workspace
//   4. ../../ethora-bdsm/product/ethora-sdk-android — one level further up
//
// Opt out entirely: export ETHORA_SDK_LOCAL=0 (forces JitPack even
// when a sibling exists).
//
val localSdkOptOut = (System.getenv("ETHORA_SDK_LOCAL") == "0")
val localSdkOverride = System.getenv("ETHORA_SDK_LOCAL_PATH")
    ?.takeIf { it.isNotBlank() }
    ?.let { file(it) }

val localSdkCandidates = listOfNotNull(
    localSdkOverride,
    rootDir.resolve("../ethora-sdk-android"),
    rootDir.resolve("../ethora-bdsm/product/ethora-sdk-android"),
    rootDir.resolve("../../ethora-bdsm/product/ethora-sdk-android")
)

val localSdkDir = if (localSdkOptOut) null
    else localSdkCandidates.firstOrNull { it.resolve("settings.gradle.kts").exists() }

if (localSdkDir != null) {
    // The included SDK build is an independent Gradle project with its
    // own AGP configuration, so it needs its own local.properties with
    // sdk.dir. Inherit it from this sample's local.properties / env if
    // the SDK dir doesn't already have one — otherwise AGP fails during
    // configuration with "SDK location not found", which in turn cascades
    // into 'Could not isolate parameters of D8BackportedMethodsGenerator'.
    fun findAndroidSdkDir(): File? {
        // 1. Sample's own local.properties
        val sampleProps = rootDir.resolve("local.properties")
        if (sampleProps.isFile) {
            val props = java.util.Properties().apply {
                sampleProps.reader().use { load(it) }
            }
            props.getProperty("sdk.dir")
                ?.let { File(it) }
                ?.takeIf { it.isDirectory }
                ?.let { return it }
        }
        // 2. ANDROID_HOME / ANDROID_SDK_ROOT env vars
        listOfNotNull(System.getenv("ANDROID_HOME"), System.getenv("ANDROID_SDK_ROOT"))
            .map { File(it) }
            .firstOrNull { it.isDirectory }
            ?.let { return it }
        // 3. Default install locations
        val home = System.getProperty("user.home")
        return listOf(
            File(home, "Library/Android/sdk"),          // macOS
            File(home, "Android/Sdk")                   // Linux
        ).firstOrNull { it.isDirectory }
    }

    val sdkLocalProps = localSdkDir.resolve("local.properties")
    if (!sdkLocalProps.isFile) {
        val androidSdk = findAndroidSdkDir()
        if (androidSdk != null) {
            sdkLocalProps.writeText(
                """
                |# Auto-generated by ethora-sample-android/settings.gradle.kts for composite builds.
                |# Safe to delete or edit — sync will recreate it from the sample's local.properties
                |# or from ANDROID_HOME if missing.
                |sdk.dir=${androidSdk.absolutePath}
                |
                """.trimMargin()
            )
            logger.lifecycle(
                "ethora-sample-android: wrote sdk.dir=${androidSdk.absolutePath} to " +
                    "${sdkLocalProps.canonicalPath} (needed for included-build AGP configuration)"
            )
        } else {
            logger.warn(
                "ethora-sample-android: could not locate Android SDK for included build at " +
                    "${localSdkDir.canonicalPath}. Set ANDROID_HOME, or create the SDK's " +
                    "local.properties manually with sdk.dir=..., or export ETHORA_SDK_LOCAL=0 " +
                    "to force JitPack mode."
            )
        }
    }

    logger.lifecycle(
        "ethora-sample-android: using local SDK source at ${localSdkDir.canonicalPath} " +
            "(set ETHORA_SDK_LOCAL=0 to use JitPack instead)"
    )
    includeBuild(localSdkDir) {
        dependencySubstitution {
            substitute(module("com.github.dappros:ethora-sdk-android"))
                .using(project(":ethora-component"))
        }
    }
} else {
    logger.lifecycle(
        "ethora-sample-android: no local ethora-sdk-android checkout found — " +
            "using the JitPack SDK artifact pinned in app/build.gradle.kts."
    )
}
